---
- name: Install needed packages
  yum:
    name:
      - python3-pip
      - openssl-devel
      - make
      - podman
      - skopeo
      - jq
      - git
    state: present

- name: install httpd
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-httpd"
  when: virtualmedia_over_http is defined and virtualmedia_over_http|bool == True

- name: install racadm
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-racadm"
  when: need_racadm|bool == True

- name: install aicli
  include_role:
    name: "{{ playbook_dir }}/../common-roles/install-aicli"

- name: Install provisioner cluster
  include_role:
    name: "{{ playbook_dir }}/../common-roles/create-provisioner-cluster"
  when: provisioner_cluster_name is defined and provisioner_cluster_name|length > 0 
